# Generated by Django 3.2.23 on 2023-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231102_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aficion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='interes',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='intereses',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='aficion',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interes',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='h.gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interes',
            field=models.ManyToManyField(choices=[('fiction', 'Ficción'), ('action', 'Acción'), ('comedy', 'Comedia'), ('drama', 'Drama')], to='core.Interes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='aficiones',
            field=models.ManyToManyField(choices=[('natacion', 'Natación'), ('basket', 'Basket'), ('lectura', 'Lectura'), ('fulbol', 'Fútbol')], to='core.Aficion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=6),
        ),
    ]
